blank_issues_enabled: false
contact_links:
  - name:  Discussions
    url: https://github.com/<your-username>/<repo-name>/discussions
    about: Please use discussions for questions and general ideas.
